flask:
  image: adolgarev/python2:1473852567
  volumes:
    - ./:/web
  expose:
    - "5000"
  ports:
    - "5000:5000"
    - "1234:1234"
  command: /bin/bash -c "cd /web && pip install -r requirements.txt && export FLASK_APP=server/server.py &&
        flask run --host=0.0.0.0"
node:
  image: node:4.5.0
  volumes:
    - ./:/web
  links:
    - flask:flask
  expose:
    - "3000"
  ports:
    - "3000:3000"
  command: /bin/bash -c "cd /web/client/ && npm install && npm run build && npm run start"